name: "Navicat Premium"
description: "Install and run Navicat Premium"

runs:
  using: "composite"
  steps:
    - name: Setup local taps
      run: |
        mkdir -p taps
        curl -o taps/navicat-premium.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/HEAD/Casks/n/navicat-premium.rb
        sed -i '' '/zap trash/,/]/d' taps/navicat-premium.rb
        sed -i '' '/^$/d' taps/navicat-premium.rb
      shell: bash

    - name: Install Navicat Premium
      run: |
        brew install --cask $(pwd)/taps/navicat-premium.rb
        ls -la /Applications | grep Navicat
        defaults read /Applications/Navicat\ Premium.app/Contents/Info | grep Version
      shell: bash

    - name: Open Navicat Premium
      run: open -a /Applications/Navicat\ Premium.app && sleep 10
      shell: bash

    - name: Is Navicat Premium running?
      run: |
        pgrep -fl Navicat
        ps aux | grep Navicat
      shell: bash
