name: Matrix Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-latest-large
    steps:
      - name: Get System Information
        run: |
          uname -a
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Arch: ${{ runner.arch }}"
          echo "Matrix OS: ${{ matrix.os }}"
          echo "Matrix Arch: ${{ matrix.arch }}"