name: Navicat Premium

on:
  workflow_call:

jobs:
  install:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup local taps
        run: |
          mkdir -p taps
          curl -o taps/navicat-premium.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/HEAD/Casks/n/navicat-premium.rb
          sed -i '' '/zap trash/,/]/d' taps/navicat-premium.rb
          sed -i '' '/^$/d' taps/navicat-premium.rb

      - name: Install Navicat Premium
        run: |
          brew install --cask $(pwd)/taps/navicat-premium.rb
          ls -la /Applications | grep Navicat
          defaults read /Applications/Navicat\ Premium.app/Contents/Info | grep Version

      - name: Open Navicat Premium
        run: open -a /Applications/Navicat\ Premium.app && sleep 3

      - name: Is Navicat Premium running?
        run: |
          pgrep -fl Navicat
          ps aux | grep Navicat