name: Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "release/*"

concurrency:
  group: release-${{ github.ref_name }}

env:
  DRY_RUN: ${{ startsWith(github.event.ref, 'refs/tags/v') && '0' || '1' }}
  GITHUB_TOKEN: ${{ secrets.ISO_GH_CLI_TOKEN || secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.ISO_GH_CLI_TOKEN || secrets.GITHUB_TOKEN }}
  COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
  COSIGN_PWD: ${{ secrets.COSIGN_PWD }}

jobs:
  release:
    name: ${{ matrix.name }}
    timeout-minutes: 10
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: release (Ubuntu Latest)
            runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup gpg
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v7.0.0
        with:
          gpg_private_key: ${{ secrets.ISO_GPG_KEY }}
          passphrase: ${{ secrets.ISO_GPG_PWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Install git-cliff
        uses: taiki-e/install-action@v2.68.26
        with:
          tool: git-cliff

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.0

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v7.0.0
        with:
          install-only: true

      - name: Run the release script
        run: scripts/release.sh
