name: Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'gh_actions'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest]
        go-version: [1.23.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set the GITHUB_TOKEN environment variable for the Go code
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: All list of ~/Library/Preferences
        run: ls -la ~/Library/Preferences

      - name: Setup local taps
        run: |
          mkdir -p taps
          curl -o taps/navicat-premium.rb https://raw.githubusercontent.com/Homebrew/homebrew-cask/HEAD/Casks/n/navicat-premium.rb
          sed -i '' '/zap trash/,/]/d' taps/navicat-premium.rb
          sed -i '' '/^$/d' taps/navicat-premium.rb

      - name: Install Navicat Premium
        run: |
          brew install --cask $(pwd)/taps/navicat-premium.rb

      - name: Test
        run: |
          go run *.go