name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest]
        go-version: [1.23.x]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
      HOMEBREW_CASK_OPTS: '--no-quarantine'

    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Navicat Premium
        run: |
          brew config
          brew install --cask navicat-premium
          brew info navicat-premium
          brew list
          brew search navicat-premium

      - name: Test
        run: |
          go run *.go