name: Release PLZ

on:
  push:
    branches:
      - main

concurrency:
  group: release-plz

env:
  GITHUB_TOKEN: ${{ secrets.ISO_GH_CLI_TOKEN || secrets.GITHUB_TOKEN }}

jobs:
  release-plz:
    name: ${{ matrix.name }}
    timeout-minutes: 10
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: release-plz (Ubuntu Latest)
            runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.ISO_GH_CLI_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup gpg
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.ISO_GPG_KEY }}
          passphrase: ${{ secrets.ISO_GPG_PWD }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Install git-cliff
        uses: taiki-e/install-action@v2.47.5
        with:
          tool: git-cliff

      - name: Run the release-plz script
        run: scripts/release-plz.sh
