name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest]
        go-version: [1.23.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: true
          test-bot: true

      - name: Install Navicat Premium
        run: |
          brew config
          brew install --cask navicat-premium

      - name: Test
        run: |
          go run *.go