name: Test

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit:
    name: ${{ matrix.name }}
    timeout-minutes: 10
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: unit (Macos Latest)
            runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Required software for Navicat Premium
        uses: ./.github/actions/navicat-premium

      - name: Run unit tests
        run: go run *.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
