name: Test

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - "gh_actions"

jobs:
  unit:
    strategy:
      matrix:
        os: [macos-latest]
        go-version: [1.23.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Required software for Navicat Premium
        uses: ./.github/actions/navicat-premium

      - name: All list of /Applications
        run: ls -la /Applications

      - name: All list of ~/Library/Preferences
        run: ls -la ~/Library/Preferences

      - name: All list of ~/Library/Application Support
        run: ls -la ~/Library/Application\ Support

      - name: Is Navicat Premium running?
        run: |
          pgrep -fl Navicat
          ps aux | grep Navicat

      - name: Install Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: false

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: go run *.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}